export const ADD_PROFILE_POST = 'ADD-PROFILE-POST';
export const UPDATE_PROFILE_TYPING_TEXTAREA = 'UPDATE-PROFILE-TYPING-TEXTAREA';
export const PROFILE_PAGE_SET_USER_INTO_STATE = 'PROFILE-PAGE-SET-USER-INTO-STATE';
export const PROFILE_PAGE_IS_PRELOADER_ACTIVE = 'PROFILE-PAGE-IS-PRELOADER-ACTIVE';
export const PROFILE_PAGE_GET_USER_STATUS = 'PROFILE-PAGE-GET-USER-STATUS';
export const PROFILE_PAGE_SET_USER_STATUS_INTO_STATE = 'PROFILE-PAGE-SET-USER-STATUS-INTO-STATE';